### PR TITLE
Maven 4

### PR DESCRIPTION
**Pull request by velo**
Attempt to fix https://github.com/sundrio/sundrio/issues/481 

To make sure it was tested with maven 4 I upgrade the wrapper

```
mvn org.apache.maven.plugins:maven-wrapper-plugin:3.3.2:wrapper -Dmaven=4.0.0-rc-2
```

not sure if that is something project is happy with right now, but can be rolled back

### CODE REVIEW

**Comment by gnodet** [comment]
I confirm this PR fixes the library for Maven 4 consumption and build with 4.0.0-rc-2.  When 4.0.0-rc-3 is out, some plugins will have to be updated as well, see #494 (mostly the old `maven-shade-plugin` which fails the build with rc-3-SNAPSHOT).

**Comment by gnodet** [comment]
@velo could you open your repository for me so that I can push to your PR ?
Or apply this diff:

```diff
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
index 63eb6d33..824c8fbf 100644
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,7 +29,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        java: [17,21,23]
+        java: [11,17,21,23]
         profile: [normal, with-swagger]
     steps:
       - name: Checkout
diff --git a/pom.xml b/pom.xml
index 3b22e927..10e28707 100644
--- a/pom.xml
+++ b/pom.xml
@@ -135,7 +135,8 @@
                 <artifactId>maven-compiler-plugin</artifactId>
                 <version>${maven-compiler-plugin.version}</version>
                 <configuration>
-                    <release>11</release>
+                    <source>11</source>
+                    <target>11</target>
                     <!-- The option below starting causing `Unknown compilation error` as soon as SourceVersion annotations were removed
                          in favor of SourceVersion.latest().
                          According to: https://stackoverflow.com/questions/56646698/what-causes-an-unknown-compilation-problem-occurred the
```

**Comment by velo** [comment]
Rebased, should have fixed that

**Comment by gnodet** [comment]
@velo please disable build with Maven 4, some tests don't work, see https://github.com/sundrio/sundrio/pull/495

**Comment by iocanel** [comment]
Merged #495 so I am closing this one. Thanks a lot @velo and @gnodet
